### ISSUE TITLE
Publish driver to Maven central and or jcenter

### ISSUE THREAD

**Issue by magJ** [aws/amazon-redshift-jdbc-driver#10]
## Driver version
N/A. Publish all versions, or all new versions.

## Redshift version
N/A

## Client Operating System
N/A

## JAVA/JVM version
N/A

## Table schema
N/A

## Problem description
Driver binaries are currently only made available via the redshift documentation website/S3.

This makes it more difficult to obtain the driver, and keep up to date with the latest versions.
Build tools(maven/gradle) need to have a new repository configured with the repo details.

Publishing the driver on a mainstream repo would make it a lot easier to use.

## JDBC trace logs
N/A

## Reproduction code
N/A

**Comment by iggarish** [comment]
Thanks for informing your concern. Yes we are looking into publishing driver in Maven Central. We have some process to follow and we are working on it.

**Comment by iggarish** [comment]
We just released 2.0.0.3 to the Maven Central. Please check.
https://mvnrepository.com/artifact/com.amazon.redshift/redshift-jdbc42/2.0.0.3
https://repo1.maven.org/maven2/com/amazon/redshift/redshift-jdbc42/2.0.0.3/

**Comment by magJ** [comment]
Yup, works, thanks!
