### ISSUE TITLE
AmazonRedshiftClientBuilder: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by akuzin1** [aws/amazon-redshift-jdbc-driver#101]
## Driver version
2.1.0.19
2.1.0.21

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.57798	

## JAVA/JVM version
Java 11

## Problem description

Would like to connect to Redshift using JDBC driver via IAM.

As specified by IAM jdbc URL documentation: https://docs.aws.amazon.com/redshift/latest/mgmt/jdbc20-configure-authentication-ssl.html

Resulting in the following error when adding `iam` to the connection string.

```
java.lang.NoClassDefFoundError: com/amazonaws/services/redshift/AmazonRedshiftClientBuilder
	at com.amazon.redshift.jdbc.RedshiftConnectionImpl.<init>(RedshiftConnectionImpl.java:282)
	at com.amazon.redshift.Driver.makeConnection(Driver.java:481)
	at com.amazon.redshift.Driver.connect(Driver.java:302)
	at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
```

Am able to connect just fine, when leaving out `iam` and providing user and password parameters.
Using the following format `jdbc:redshift:iam:// [host]:[port]/[db]?key1=value1&key2=value2`

**Comment by bhvkshah** [comment]
@akuzin1 do you have all files in the .zip suite in your classpath or just the .jar? For IAM auth you will need the additional dependencies that ship with the driver. You can download this suite at: https://docs.aws.amazon.com/redshift/latest/mgmt/jdbc20-download-driver.html

**Comment by akuzin1** [comment]
Yes, the driver dependencies should be included .
