### ISSUE TITLE
Connections randomly set to read-only using version 1.2.51.1078

### ISSUE THREAD

**Issue by mgirard772** [aws/amazon-redshift-jdbc-driver#11]
## Driver version
https://s3.amazonaws.com/redshift-downloads/drivers/jdbc/1.2.51.1078/RedshiftJDBC42-1.2.51.1078.zip

## Redshift version
1.0.23412

## Client Operating System
MacOS 10.15.7

## JAVA/JVM version
9.0.4

## Problem description
1. **Expected behavior**: Connections started as read/write stay read/write
2. **Actual behavior**: Connections started as read/write end up as read-only, seemingly at random
3. **Error message/stack trace**:  See below
4. **Any other details that can be helpful**: 
Re: https://github.com/dbeaver/dbeaver/issues/11264
Resolved by using https://s3.amazonaws.com/redshift-downloads/drivers/jdbc/1.2.45.1069/RedshiftJDBC42-no-awssdk-1.2.45.1069.jar

![image](https://user-images.githubusercontent.com/24948365/107377547-180e0c80-6ab9-11eb-86c5-ee68938fcc67.png)

**Comment by iggarish** [comment]
Thanks for reporting the issue. The open source base is for the 2.x driver. Could you please try 2.x driver for the same?

**Comment by iggarish** [comment]
Closing this issue as it's not for 2.x driver.
