### ISSUE TITLE
Dbeaver error with Redshift driver "userSetServerless" is null

### ISSUE THREAD

**Issue by bkenny1** [aws/amazon-redshift-jdbc-driver#114]
## Driver version
redshift-jdbc42-2.1.0.25

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.63269

## Client Operating System
Windows 10

## JAVA/JVM version
 java version "1.8.0"

## Problem description

1. Expected behaviour:
When connecting from Dbeaver using current jdbc driver redshift-jdbc42-2.1.0.25 I should be able to connect successfully using SAML. We currently using the driver redshift-jdbc42-2.1.0.19 and that can connect successfully. 

3. Actual behaviour:
When connecting from Dbeaver using updated jdbc driver 42-2.1.0.25 we get the error below. 

5. Error message/stack trace:
Cannot invoke "String.equalsIgnoreCase(String)" because "userSetServerless" is null

7. Any other details that can be helpful:
DBeaver Version 24.0.0.202403091004 
The Cluster type is a Redshift Provisioned cluster (dc2.large) ie not serverless and the error seems to be related to a serverless parameter which should not be applicable.

**Comment by bkenny1** [comment]
Hi @bhvkshah 
Thanks. I have the logs available, how do I provide them? As an attachment in the comments?

**Comment by bhvkshah** [comment]
Yes, that works

**Comment by bkenny1** [comment]
[Error log userSetServerless.txt](https://github.com/aws/amazon-redshift-jdbc-driver/files/14618291/Error.log.userSetServerless.txt)
Logs attached @bhvkshah, thanks for your help

**Comment by bhvkshah** [comment]
Thanks for the update. We'll have a fix for this in the next release.

**Comment by eric-riggan** [comment]
Update (for support team and in case others see this)

Was able to temporarily resolve.
DBeaver version: 23.3.5
Manually set DBeaver Maven Redshift driver version to 2.1.0.26
Manually download, unzipped, and add files from redshift-jdbc42-2.1.0.26 to driver manager.
Successfully configured and connected to our cluster via BrowserSAMLAuthentication with login_url parameter and SSL configured

**Comment by mike-eh2** [comment]
My team has been struggling with the same issue on Mac, but finally got it working today. Switching to DBeaver v23.3.5 did not help, but switching the redshift driver to v2.1.0.26 did work.

**Comment by bsharifi** [comment]
Resolved with 2.1.0.28 release.

**Comment by bryangeiger** [comment]
Seeing same issues with DBeaver Version 24.1.1.202406231636 and jdbc driver 2.1.0.29

**Comment by bryangeiger** [comment]
downgraded to jdbc driver 2.1.0.28 with DBeaver Version 24.1.1.202406231636 and its working, thank you.
