### ISSUE TITLE
2.1.0.27 release

### ISSUE THREAD

**Issue by wendigo** [aws/amazon-redshift-jdbc-driver#116]
I just noticed that there is a new release in the maven central (2.1.0.27): https://repo1.maven.org/maven2/com/amazon/redshift/redshift-jdbc42/

There is no corresponding tag in this repository nor the changelog. How can I verify that this is a genuine release?

**Comment by wendigo** [comment]
cc @bhvkshah

**Comment by bsharifi** [comment]
Hi @wendigo 
This release was created in error. We will add a note to the changelog to reduce confusion as this driver is not recommended for use.
