### ISSUE TITLE
After successful connect with AccessKey/SecretAccessKey (IAM) a following connect using invalid keys still connect

### ISSUE THREAD

**Issue by rogerbj** [aws/amazon-redshift-jdbc-driver#12]
## Driver version
2.0.0.3
## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.24265

## Client Operating System
macOS

## JAVA/JVM version
Java 14

## Problem description
1. Expected behaviour: After a successful connect with IAM and AccessKey, SecretAccessKey, changing any of these to a bogus key and connect again should fail in the same Java session
2. Actual behaviour: Connect with correct keys works fine, disconnect and then connect again with bogus keys (in same JVM) still connects successfully. Debugging the JDBC URL at connect shows the bogus keys but still the connect works fine.

Is this the expected behaviour?

**Comment by iggarish** [comment]
Thanks for reporting issue. Could you please generate JDBC driver logs? You can add LogLevel=6 and LogPath-<my_dir> in the URL. Here <my_dir> replace with any existing directory.

**Comment by iggarish** [comment]
We can reproduce the issue and working on it. The fix will be available in 2.0.0.4, which will release end of this month.

**Comment by rogerbj** [comment]
@iggarish great!

**Comment by iggarish** [comment]
Released 2.0.0.4 version. Check README file for the download links.
