### ISSUE TITLE
Driver not bundled with SDK in Maven central

### ISSUE THREAD

**Issue by xidex** [aws/amazon-redshift-jdbc-driver#17]
## Driver version
2.0.0.4

## Redshift version
N/A

## Client Operating System
N/A

## JAVA/JVM version
N/A

## Problem description

1. I would like to ask you why do you ship JDBC driver v2 without required libraries under same groupId+artifactId combination as v1 which was bundled with the required libraries?

**Comment by iggarish** [comment]
Hi Slavomir,

We don't ship fat jar even in 1.x from/after 1.2.47.1071 releases. Now we are shipping driver jar and for IDP users we ship driver zip file. This zip file contains driver jar and all dependencies jars. This help customers to see which are all dependencies of the driver and if there is any conflicting of dependency, user can easily fix it. Also for Maven central we never release driver. Some other company did it. We also provide sample pom file, so user can put dependencies in their pom file, as Maven meant for to list dependencies. 

Thanks,
ilesh Garish

**Comment by xidex** [comment]
Hi @iggarish ,
where I can find that sample pom file you mentioned?
Thanks.

**Comment by iggarish** [comment]
For 2.x:
https://redshift-maven-repository.s3.amazonaws.com/release/com/amazon/redshift/redshift-jdbc42/2.0.0.4/redshift-jdbc42-2.0.0.4.pom

For 1.x:
https://redshift-maven-repository.s3.amazonaws.com/release/com/amazon/redshift/redshift-jdbc42-no-awssdk/1.2.54.1082/redshift-jdbc42-no-awssdk-1.2.54.1082.pom
