### ISSUE TITLE
Execute batch with composite query fails.

### ISSUE THREAD

**Issue by xidex** [aws/amazon-redshift-jdbc-driver#18]
## Driver version
2.0.0.4

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.25813

## Client Operating System
Mac OS 10.15.7

## JAVA/JVM version
1.8.0

## Table schema
test_table(id VARCHAR(10), description VARCHAR(20))

## Problem description
When I add multiple commands into a single `Statement#addBatch(String sql)` call and then I execute it, the driver fails with `com.amazon.redshift.util.RedshiftException: Too many update results were returned.`. Actually, I found a bug in the code which allowed multiple commands be passed into a single `addBatch` call because previous v1 driver handled it and divided the composite query into subqueries and executed them correctly. The bug is already fixed so this is not a problem for me anymore but I just wanted to check with you guys if it's something the v2 driver should handle as well?

## JDBC trace logs
[redshift_jdbc_connection_1.log](https://github.com/aws/amazon-redshift-jdbc-driver/files/6419864/redshift_jdbc_connection_1.log)
[redshift_jdbc.log](https://github.com/aws/amazon-redshift-jdbc-driver/files/6419865/redshift_jdbc.log)

## Reproduction code
```
public void executeBatchWithCompositeQuery() throws SQLException {
        Connection conn = null;
        Statement stmt = null;
        try {
            Properties props = new Properties();
            props.setProperty("user", dbUsername);
            props.setProperty("password", dbUserPassword);
            conn = DriverManager.getConnection(dbURL, props);

            stmt = conn.createStatement();

            stmt.execute("CREATE TABLE test_table(id VARCHAR(10), description VARCHAR(20))");
            stmt.execute("INSERT INTO test_table VALUES ('1', 'First item')");
            stmt.execute("INSERT INTO test_table VALUES ('2', 'Second item')");
            stmt.execute("INSERT INTO test_table VALUES ('3', 'Third item')");

            stmt.addBatch("UPDATE test_table SET description='Haha' where id='2';UPDATE test_table SET description='Hehe' where id='3'");
            int[] ints = stmt.executeBatch();
            //Assert.assertEquals("[1, 1]", Arrays.toString(ints));
        } finally {
            if (stmt != null) {
                stmt.execute("DROP TABLE IF EXISTS test_table");
            }
            try {
                if (stmt != null)
                    stmt.close();
            } catch (Exception ex) {
            }
            try {
                if (conn != null)
                    conn.close();
            } catch (Exception ex) {
            }
        }
    }
```

**Comment by iggarish** [comment]
Thanks for reporting the issue. We will look into it and get back to you.

**Comment by iggarish** [comment]
Hi Salvomir, 

Could you please tell us use case for it? As such addBatch() meant for one command at a time in the batch. In 2.x driver couple of customer requested not to allow multiple SQL statements separated by semicolon to protect against SQL injection.

Normal use case of batch is for parametric query and in that case it's hard to allow setting parameter values for multiple commands separated by semicolon.

Thanks,
ilesh garish

**Comment by xidex** [comment]
I don't have a use case for it. As I said previously I found a bug in my code thanks to v2 driver because it worked differently than v1 version. And the sole reason to report it was just to let you know that there's this difference between versions.
I am fine with the current behavior.
Thanks.

**Comment by iggarish** [comment]
Thanks for details. I am closing this issue for now. Feel free to reopen in future if you think it needs to fix.
