### ISSUE TITLE
Fetch Ring Buffer Documentation

### ISSUE THREAD

**Issue by josephlbarnett** [aws/amazon-redshift-jdbc-driver#20]
## Driver version
2.0.0.4

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.26065

## Client Operating System
Amazon Linux AMI release 2018.03

## JAVA/JVM version
openjdk 1.8.0

## Problem description
Since moving to driver 2.x, have noticed increased memory usage leading to OOMs on a relatively small heap JVM.  It appears that disabling the "fetch ring buffer" alleviates the issues, but would like to know if there's any documentation on how the fetch ring buffer works, and what tradeoffs/side-effects might occur when it's disabled.

Thanks!

**Comment by iggarish** [comment]
Hi Joe,

Thanks for reporting the problem. Following parameters are for fetch ring buffer:
1. enableFetchRingBuffer. As you found, this parameter is enable by default to limit fetch rows by size or by count. 
2. fetchRingBufferSize. This is limit the ring buffer size. Default value is 1G i.e. 1GB. When this size is given then buffer limit by size. You can provide value 0 then when enableFetchRingBuffer is enable the ring buffer limit by count and here count is taken in account by fetch size.

So in your case when there is low JVM heap, I suggest to limit fetchRingBufferSize. You can find info about this parameter here:
https://docs.aws.amazon.com/redshift/latest/mgmt/jdbc20-configuration-options.html#jdbc20-fetchringbuffersize-option

If you disable ring buffer fetch then all rows will be in memory. So memory consumption depends on your size of result set. In our testing we found that ring buffer fetch cap the memory consumption depending upon the configuration of fetchRingBufferSize and fetch size. So here is the summary:
1. enableFetchRingBuffer=true and fetchRingBufferSize>0 then driver cap the resultset by ring buffer size.
2. enableFetchRingBuffer=true and fetchRingBufferSize=0  then driver cap the resultset by number of rows i.e. fetch size.
3. enableFetchRingBuffer=false then driver fetch all rows in memory, if fetch size is 0. If fetch size is greater then 0 then it becomes server side cursor and fetch in batches of "fetch size".

Definitely we can document this behavior.

If you can share your repro case, we can dig more and look into it.

Thanks,
ilesh Garish

**Comment by josephlbarnett** [comment]
Thanks Ilesh, that's a helpful explanation.  What is the fetch ring buffer's lifecycle tied to? (static to full JVM/connection/something else?)

Our use case involves setting fetch size on a query that can potentially return many rows and "streaming" results back over a websocket to a connected client.  

Our observations so far:

1. enableFetchRingBuffer=true, default 1G fetchRingBufferSize: a single large query can OOM the small VM (heap is < 1G so fetchRingBufferSize gets set to 90% of heap and quickly exhausts heap)
2. enableFetchRingBuffer=true, fetchRingBufferSize=5percent: a single large query is ok but uses more than 5% more memory than case 3, but over time the VM heap gets exhausted (haven't yet tracked down fully what's happening here)
3. enableFetchRingBuffer=false: a single large query is ok, and uses less memory than with a 5percent fetch ring buffer (still evaluating long term heap health)

**Comment by iggarish** [comment]
Fetch ring buffer life cycle tied to per query. When query returns a row, the driver creates a queue for rows and keep adding rows in it. When application fetch the row, the driver removes the row from the queue. Once result has been close, we close this queue. This queue we refer as ring buffer. So it keeps growing when the driver reads a row from the connection socket and when application fetch the result, the driver remove the row from this queue and it shrinks. This queue can grow up to size defined. This size is only for rows and it's based on network buffer size of rows. There may be some overhead of java classes as the driver couldn't estimate exact size of this buffer queue. The driver allows only one query run per connection at a time, but if multiple connections active at same time then it is possible multiple queries in the driver running in parallel and it has multiple ring buffers active.

**Comment by josephlbarnett** [comment]
Ok thanks.  Good to know its potentially one buffer per connection.  Note that "more than 5% more memory" was actually much more than 5% -- heap usage got up to ~80% pretty quickly, vs hovering around ~30% without the fetch ring buffer.

other than the memory usage differences, are there other behavior changes we should be watching out for with the fetch ring buffer disabled and a fetch size > 0 set?

**Comment by iggarish** [comment]
If you disable fetch ring buffer than response time will be high depends on fetch size. Ring buffer uses dual threads, one application thread and another thread to fetch from the socket. So response time is faster.

**Comment by iggarish** [comment]
Closing the issue.
