### ISSUE TITLE
JDBC IAM Auth to Redshift does not work with the "Profile" connection attribute.

### ISSUE THREAD

**Issue by madhavvishnubhatta** [aws/amazon-redshift-jdbc-driver#26]
## Driver version
2.0.0.4

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.26742

## Client Operating System
Amazon Linux 2
I am using the AMI - amzn2-ami-hvm-2.0.20210126.0-x86_64-gp2
output of `uname -a` is:
Linux ip-172-31-90-114.ec2.internal 4.14.214-160.339.amzn2.x86_64 #1 SMP Sun Jan 10 05:53:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

## JAVA/JVM version
openjdk version "11.0.9" 2020-10-20 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.9+11-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.9+11-LTS, mixed mode, sharing)

## Table schema
Not Applicable to this issue

## Problem description
I am trying to use JDBC to connect to a Redshift cluster using IAM Authentication. The code is given below. The code works when the EC2 on which I am running this has an IAM role attached which has permissions for GetClusterCredentials. But when I run the code using the "Profile" JDBC connection attribute after configure an IAM user using the `aws configure --profile profilename` option providing a static set of access key and secret access id, it does not work. I get a JDBC error given below.
1. Expected behaviour: I expect the connection to succeed and print the result of the query `SELECT count(*) as numcols from information_schema.columns`
2. Actual behaviour: I get an error that says `Exception in thread "main" com.amazon.redshift.util.RedshiftException: Something unusual has occurred to cause the driver to fail. Please report this exception.`
3. Error message/stack trace:
```
Exception in thread "main" com.amazon.redshift.util.RedshiftException: Something unusual has occurred to cause the driver to fail. Please report this exception.
        at com.amazon.redshift.Driver.connect(Driver.java:316)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:208)
        at com.mycompany.app.App.main(App.java:41)
Caused by: com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain
        at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:131)
        at com.amazon.redshift.core.IamHelper.setIAMCredentials(IamHelper.java:448)
        at com.amazon.redshift.core.IamHelper.setIAMProperties(IamHelper.java:304)
        at com.amazon.redshift.jdbc.RedshiftConnectionImpl.<init>(RedshiftConnectionImpl.java:244)
        at com.amazon.redshift.Driver.makeConnection(Driver.java:466)
        at com.amazon.redshift.Driver.connect(Driver.java:279)
        ... 3 more
```
4. Any other details that can be helpful:
I tried the same on an Ubuntu machine too, but that too did not work. I got the same error.

## JDBC trace logs
I am not sure how to enable this trace. I tried searching for this but could not find a clear answer. Can someone provide instructions on how to do this?

## Reproduction code
```java
package com.mycompany.app;

import java.sql.*;
import java.util.Properties;
import java.util.*;  

public class App {

   public static void main(String []args) throws Exception {

        Scanner sc= new Scanner(System.in);
        
        System.out.print("Enter the dbname: ");
        String db= sc.nextLine(); 
        System.out.print("Enter the DB user you want to login as: ");
        String user= sc.nextLine(); 
        System.out.print("Enter the user profile you want to use [Hit enter for default]: ");
        String profile= sc.nextLine();
        System.out.print("Enter the value of AutoCreate parameter: ");
        String autocreate= sc.nextLine();
        if (profile.length() == 0) {
            profile = "default";
        }

        Class.forName("com.amazon.redshift.jdbc42.Driver");

        System.out.println("Connecting with profile: "+profile);

        //Please change the cluster endpoint here
        String url = "jdbc:redshift:iam://redshift-cluster-1.abcdefghijklm123.us-east-1.redshift.amazonaws.com:5439/"+db;
        Properties properties = new Properties();
        properties.setProperty("DbUser", user);
        properties.setProperty("AutoCreate", autocreate);
        properties.setProperty("Profile", profile);
        properties.setProperty("Trace", "on");
        Connection connection = DriverManager.getConnection(url, properties);

        System.out.println("Using IAM");
        System.out.println("Creating statement...");
        Statement stmt = connection.createStatement();
        String sql;
        
        //1st query
        sql = "SELECT count(*) as numcols from information_schema.columns";
        ResultSet rs = stmt.executeQuery(sql);

        //STEP 5: Extract data from result set
        while(rs.next()){
         //Retrieve by column name
         int numcols  = rs.getInt("numcols");
         //Display values
         System.out.println("Count: " + numcols);
        }
   }
}

```

**Comment by iggarish** [comment]
In the URL put: "LogLevel=6;Logpath=/some_exist_dir

LogPath must be exist. Then run your test and it should create redshift*.log in that directory.

In your case URL become:
String url = "jdbc:redshift:iam://redshift-cluster-1.abcdefghijklm123.us-east-1.redshift.amazonaws.com:5439/"+db + ";LogLevel=6;Logpath=/some_exist_dir";

**Comment by iggarish** [comment]
Also can you try lower case profile as prop name?
properties.setProperty("profile", profile);

**Comment by madhavvishnubhatta** [comment]
Thanks @iggarish. Changing the case of the Profile connection attribute solved the issue. And also thank you for showing how to enable trace log. Should this issue still be marked as a bug since [the documentation](https://docs.aws.amazon.com/redshift/latest/mgmt/jdbc20-configuration-options.html#jdbc20-profile-option) uses upper case P for profile? I am ok with closing this if you think this is not a bug, please let me know.

**Comment by iggarish** [comment]
Keep the issue open. I will check case sensitivity of prop name in the code and see it's ok to change code otherwise we will change the doc.

**Comment by iggarish** [comment]
Change the code to support "profile" as well "Profile" as key in connection property. Fix will available in next release i.e. 2.0.0.7.
