### ISSUE TITLE
The table is created with Default column size(256) in redshift rather max size of the column from source table and it's taking 3 hours to load 20k records

### ISSUE THREAD

**Issue by aiisyourfuture** [aws/amazon-redshift-jdbc-driver#28]
## Driver version
2.0.0.6

## Problem description

1. Expected behaviour:
2. Actual behaviour:
3. Error message/stack trace:
4. Any other details that can be helpful:

## JDBC trace logs
+++++++++++++++

INSERT INTO tcms_fpl.tcms_fpl_dynamic1 ("tkt_date","ticket","int_type","tkt_typ_cd","pwr_off_dt","tkt_rest_dt","tkt_restor_dttm","cmi","ci","out_min","cause_cd","eqp_cd","supt_cd","invgtr_id","crew_trk_number","svc_ctr","oper_area_cd","feeder","tkt_dvc_id","fpl_id","ra_dvc_coor","disp_trbl_cmnts","serv_ctr_cmnts","tkt_oh_ug","adverse_flag","refr_ind","tkt_ref_w_cust_out","tkt_cncl_flg","corp_excl","part_on_flag","tlm_error_flag","dw_tkt_key","em_cause","em_equipment","em_support","device_lat","device_long","total_calls","veg_allocation_flag","veg_allocation_date") VALUES ('2021-01-01 12:39:01',261.0,'SV','NLS','2021-01-01 17:46:00','2021-01-01 20:35:00','2021-01-01 20:35:00',169.0,1.0,169.0,'189','111','301','WE8182','WE8139','WEO','WD','805632','86152932501','45008548',NULL,'c("NEED REPLACE CONNS AT O/H POLE.. O/H TO URD SERV.. 122/100 RIGHT LUG.. NO REPAIRS AT POLE 150'' 1/0 URD SERV.. DOWN POLE AROUND POOL TO URD METERCAN.. R/O 3211 SW 103 CT ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_meter_can ** 350_ft_ground_strap_pole_to_mete", 
"none")','c("250 ft gstrap pole to meter", "TO BE WORKED ON WR# 10159510 ** County\tTicket #\tI Work Order #\tM/A\tComp Date\tBORE FT\tSplice / Replace\tSplice Qty\tConduit Ft\tCable Ftg\tSecondary Footage\tPT / GS\tComments\tS R D\tWR #\tDirect Buried  DADE\t261\t10159510\tWD\t1/6/2020\t168''\tREPLACE\t0\t168''\t213''\t0\tGS\t\t1/22/21\t10159510\tY Customer is back in regular service. GS removed PH to MT. Bulk completed by gxc0lac on 08:19:00 01/08/2021. Bulk completed follow up actions:  (Replace 150 ft 1/0TPX SEC)."
)','OH',NULL,'Y','Y','N','N','N','N',1.3498822E7,NULL,NULL,NULL,NULL,NULL,1.0,'N',NULL) 

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

was aborted: ERROR: Value too long for character type
  Detail: 
  -----------------------------------------------
  error:  Value too long for character type
  code:      8001
  context:   Value too long for type character varying(2056)
  query:     955369
  location:  string.cpp:183
  process:   padbmaster [pid=13698]
  -----------------------------------------------
  Call getNextException to see other errors in the batch.
	at com.amazon.redshift.jdbc.BatchResultHandler.handleCompletion(BatchResultHandler.java:195)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:609)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.internalExecuteBatch(RedshiftStatementImpl.java:978)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeBatch(RedshiftStatementImpl.java:1006)
	at com.amazon.redshift.jdbc.RedshiftPreparedStatement.executeBatch(RedshiftPreparedStatement.java:1728)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:687)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:856)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:854)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1020)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1020)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2242)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

**Comment by iggarish** [comment]
Thx for reporting the issue. Looks like table creation issue is more in server side than driver. For the performance issue, could you please generate logs with limited sample data?

**Comment by aiisyourfuture** [comment]
as per your request , i created small dataset which has 1000 records and i tried to load the data in redshift but it took almost 10 min but still does jnot finish the job so i cancelled it .pls find requested attached logs.
[redshift_jdbc_connection_1.log](https://github.com/aws/amazon-redshift-jdbc-driver/files/6750921/redshift_jdbc_connection_1.log)
[redshift_jdbc_connection_2.log](https://github.com/aws/amazon-redshift-jdbc-driver/files/6750922/redshift_jdbc_connection_2.log)
[redshift_jdbc.log](https://github.com/aws/amazon-redshift-jdbc-driver/files/6750923/redshift_jdbc.log)

**Comment by iggarish** [comment]
Thanks for the log. One thing I notice, it operate in auto commit TRUE mode. Can you try with auto commit FALSE? Then commit after some batches.

**Comment by aiisyourfuture** [comment]
here is the write statement, i specified batchsize 100 out of 1000 records and believe for each 100 records the commit happens ..even if put 1000 out 1000 same performance issue.. i just JDBC documentation to trun off autocommit but unfortunately i could not such paramaters in the documentation..

df1.write.format("jdbc").option("url", "<url>:5439/sepa_dev_db?rewriteBatchedStatements = true;LogLevel=6;LogPath=/home/spothineni/log").option("dbtable", "tcms_fpl.test2").option("user", "<user>").option("password", "<PWD>").option("batchsize",100).option("isolationLevel","NONE").mode("append").save()

**Comment by Brooke-white** [comment]
Thank you for providing the write statement. The team will look into this and get back to you next week.

**Comment by iggarish** [comment]
Autocommit OFF is JDBC standard API, so it won't be there in Redshift doc.

You can do auto commit off using setAutoCommit API call on the connection object:
e.g.
con.setAutoCommit(false);

**Comment by aiisyourfuture** [comment]
As I mentioned in the write method batch size is 1000 means it commits after 1000 records ..total no of records in dataset size is 1000..that means autocommit off indirectly still the performance is same..

**Comment by aiisyourfuture** [comment]
Hello ,

Do you need anything from my end ?

Thanks
Subbarao

**Comment by iggarish** [comment]
Hi Subbarao,

Please look into following questions:
1. Driver log shows auto commit is ON. So you need to find how you can turn it OFF from your application.
Jul 01 21:20:14.334 FUNCTION  [82 Executor task launch worker for task 0.0 in stage 0.0 (TID 0)] com.amazon.redshift.jdbc.RedshiftConnectionImpl.getAutoCommit:  Enter () 
Jul 01 21:20:14.334 FUNCTION  [82 Executor task launch worker for task 0.0 in stage 0.0 (TID 0)] com.amazon.redshift.jdbc.RedshiftConnectionImpl.getAutoCommit:  Return true 

2. Parameter rewriteBatchedStatements = true, seeing in the log is not for Redshift driver. This must be from MySQL or some other driver.

For Redshift you need to use: reWriteBatchedInserts=true. Default value is false.
You can also provide different value of reWriteBatchedInsertsSize. e.g reWriteBatchedInsertsSize=256. This should be in power of 2. Default value is 128.

3. Do you have LogLevel=6 when you actually run your test? This should be 0 to measure the performance.

4. Can you use COPY command instead of INSERT? This is the fastest way to load data in the Redshift.

Thanks,
ilesh Garish

**Comment by iggarish** [comment]
Haven't heard since long so closing the issue. If you still have the issue please re-open it.
