### ISSUE TITLE
jdbc:postgresql not working since version 2.x

### ISSUE THREAD

**Issue by Syed-SnapLogic** [aws/amazon-redshift-jdbc-driver#29]
Hello,
  I see that until redshift jdbc driver version 1.x, the jdbc url jdbc:postgre:// works.
  The moment I switch to 2.x version of the driver, I get the error. ` java.sql.SQLException: No suitable driver found for jdbc:postgresql://`

  This could break our existing integrations.  Any help on this?  Why the sub-protocol postgre not working anymore?  Is there a settiong/config that can be done in 2.x to get jdbc:postgre:// working?

  Thanks.  Also, can u point me to the commit that's not accepting jdbc:postgre?

**Comment by iggarish** [comment]
Each driver has it's own subprotocol in the driver URL. "jdbc:postgresql" is reserved for the PostgreSQL driver. 1.x driver was out source with Simba vendor. We are not sure why they decided to support both "jdbc:redshift" and "jdbc:postgresql". But when we start our own 2.x driver to open source, we just use "jdbc:redshift". This is inline with other driver where you should accept the URL for your datasource only. It was creating confusion in support team also, as it was not sure customer uses Postgresql driver or Amazon driver. Sorry no plan to support "jdbc:postgresql". Normally each tool allow to their end user to specify the URL. If your tool doesn't allow then please change URL prefix from "jdbc:postgresql" to "jdbc:redshift" as it should work with 1.x and 2.x driver.

**Comment by Syed-SnapLogic** [comment]
Thank you so much @iggarish.
