### ISSUE TITLE
null pointer exception when preparing statement for execution on Redshift 

### ISSUE THREAD

**Issue by quentindemetz** [aws/amazon-redshift-jdbc-driver#3]
## Driver version
RedshiftJDBC42-1.2.50.1077

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.21053

## Client Operating System
Linux 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 20.04

## JAVA/JVM version
```
openjdk 11.0.9 2020-10-20
OpenJDK Runtime Environment (build 11.0.9+11-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9+11-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```

## Table schema
```sql
CREATE TABLE tests (
  value numeric(15,2)
);
```

## Problem description
ref: https://forums.aws.amazon.com/thread.jspa?messageID=915052
`Null Pointer Exception` is thrown when loading data into Redshift through batch INSERT statements if first statement of the batch contains a NULL value.

## JDBC trace logs
```
Exception in thread "main" java.sql.SQLException: [Amazon][JDBC](11380) Null pointer exception.
        at com.amazon.redshift.dataengine.PGAbstractQueryExecutor.pushMappedParamTypes(Unknown Source)
        at com.amazon.jdbc.common.SPreparedStatement.updateParameterMetadata(Unknown Source)
        at com.amazon.jdbc.common.SPreparedStatement.addBatch(Unknown Source)
        at Main.main(main.java:22)
Caused by: java.lang.NullPointerException
        ... 4 more
```

## Reproduction code
```java
import java.sql.*;
import java.util.Properties;

class Main {
  private static final String JDBC_URL = "jdbc:redshift://<hostname>:5439/<database_name>";
  private static final String USERNAME = "awsuser";
  private static final String PASSWORD = "<password>";
  private static final String CLASS_NAME = "com.amazon.redshift.jdbc42.Driver";

  public static void main(String[] args) throws ClassNotFoundException, SQLException {
    Class.forName(CLASS_NAME);

    Properties properties = new Properties();
    properties.setProperty("user", USERNAME);
    properties.setProperty("password", PASSWORD);

    Connection conn = DriverManager.getConnection(JDBC_URL, properties);

    PreparedStatement ps = conn.prepareStatement("INSERT INTO tests (value) VALUES (?)");
    
    // sending null then 1.23 fails, but sending 1.23 then null works !

    ps.setObject(1, null);
    ps.addBatch();
    ps.setObject(1, 1.23);
    ps.addBatch();

    ps.executeBatch();

    conn.close();
  }
}
```

Stick this in `main.java` alongside the extracted redshift jdbc jars and run
```sh
javac -cp '.:RedshiftJDBC42-no-awssdk-1.2.50.1077.jar:aws-java-sdk-redshift-1.11.118.jar' main.java
java -cp '.:RedshiftJDBC42-no-awssdk-1.2.50.1077.jar:aws-java-sdk-redshift-1.11.118.jar' Main
```

**Comment by iggarish** [comment]
@quentindemetz  thanks for reporting issue. We will look at it and get back to you.

-- ilesh garish

**Comment by iggarish** [comment]
As per the call stack this is not 2.0 driver. You are using the 1.x driver, which is not open source. Please try with the driver build using this source code and let us know.

**Comment by quentindemetz** [comment]
I confirm 2.0 is working as expected :champagne:

**Comment by ahmadedris0** [comment]
@quentindemetz where you put the version of the driver? can you please share with me the dependency.
I am using maven and using this driver 

`
<dependency>
    <groupId>com.amazon.redshift</groupId>
    <artifactId>redshift-jdbc42-no-awssdk</artifactId>
    <version>1.2.10.1009</version>
    <scope>provided</scope>
</dependency>
`

**Comment by iggarish** [comment]
github has only 2.x driver. Following document mention about it:
https://docs.aws.amazon.com/redshift/latest/mgmt/configure-jdbc20-connection-with-maven.html

**Comment by aedris0** [comment]
Thanks, It works
