### ISSUE TITLE
Redshift JDBC Batch Insert appears slow compared to Oracle, Mysql, etc

### ISSUE THREAD

**Issue by Syed-SnapLogic** [aws/amazon-redshift-jdbc-driver#31]
## Driver version
2.0.0.7

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.28917

## Client Operating System
NAME="CentOS Linux"
VERSION="7 (Core)"

## JAVA/JVM version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

## Table schema
id (int)
name varchar(100)

## Problem description
    - I am trying to insert 100000 records into a target table.
    - I am using a PreparedStatement with a batch size of 500
    - I am parallelly executing the batch insert for three databases - Oracle, MySql and Redshift
    - All the above databases are in remote machine
    - MySql and Oracle are much faster compared to redshift
    - For oracle, its taking max 75 secs to finish injecting 100000 records into the target table
    - But redshift is taking about 40 mins for the same load

## JDBC trace logs
no logs available

## Reproduction code
    - Standalone app can be found here. https://github.com/Syed-SnapLogic/SharedChallenges/blob/master/performance/src/main/java/com/syed/test/db/performance/Executor.java
    - Credentails to be supplied thru a file
    - Modify the above source code to feed-in the credentials directly

Any reason why redshift insert is that slow compared to other databases?  Is there any config that I am missing to add to make it faster?  Please help me with if I can make it run faster, or redshift bound to be slower?

**Comment by iggarish** [comment]
Hi Syed,

Thanks for reporting issue. I look at the code and I found that auto commit is ON, i.e. default for Redshift. Can you try with c.setAutoCommit(false) and after executeBatch issue c.commit(). There are other optimization we can suggest, but let's start with this one and let us know how much difference it makes.

Thanks,
ilesh garish

**Comment by Syed-SnapLogic** [comment]
Thanks @iggarish for the inputs.  I have tried setting autocommit to false; and committing after every batch insert.  I don't see any significant improvement.  Its almost same.

```auto-commit set to false for the db redshift
connection obtained successfully for the db redshift
completed inserting batch-1 for the db redshift
performed commit for the db redshift
completed inserting batch-2 for the db redshift
performed commit for the db redshift
completed inserting batch-3 for the db redshift
performed commit for the db redshift
...
completed inserting batch-198 for the db redshift
performed commit for the db redshift
completed inserting batch-199 for the db redshift
performed commit for the db redshift
completed inserting batch-200 for the db redshift
performed commit for the db redshift
completed successfully for the db redshift in 2297741 millisecs```

Its taking ~38 mins.  And the other dbs (mysql, oracle, etc) are doing great if with autocommit true.

**Comment by iggarish** [comment]
I did one change and it finish in 73 sec.
....
completed inserting batch-195 for the db redshift
completed successfully for the db redshift in 72618 millisecs

You need to add these parameters in your URL:
";reWriteBatchedInserts=true;reWriteBatchedInsertsSize=512";
You can adjust reWriteBatchedInsertsSize as per your need.

This parameter tells driver to convert INSERT into multi tuple insert command.
Note that still you need to do :
before the loop: c.setAutoCommit(false);
and c.commit() after the executeBatch in the loop.

Let me know how it perform in your environment.

**Comment by iggarish** [comment]
Best performance will come if you have same loop  batch size and reWriteBatchedInsertsSize value. 
I did with 1024 for both and finish in 39 sec.

completed inserting batch-93 for the db redshift
completed inserting batch-94 for the db redshift
completed inserting batch-95 for the db redshift
completed inserting batch-96 for the db redshift
completed inserting batch-97 for the db redshift
completed successfully for the db redshift in 39204 millisecs


completed testing Redshift dbs

**Comment by iggarish** [comment]
Here is updated  test code:

// create table batchperftest (c1 int, c2 varchar(2048));
public class Executor {
    public static void main(String t[]) throws Exception {
			String url = TestUtil.TEST_CLUSTER_SSL_URL + ";reWriteBatchedInserts=true;reWriteBatchedInsertsSize=1024";
			String user = TestUtil.TEST_CLUSTER_USER;
			String password = TestUtil.TEST_CLUSTER_PASSWORD;
			
      Thread redshiftInsert = new Insert(url,user, password, "com.amazon.redshift.jdbc42.Driver",
              "redshift");
      redshiftInsert.start();
      redshiftInsert.join();
      System.out.println("\n\ncompleted testing Redshift dbs");
   }
}

**Comment by iggarish** [comment]
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

public class Insert extends Thread {
    private String jdbcUrl;
    private String user;
    private String passwd;
    private String driver;
    private String db;

    public Insert(String jdbcUrl, String user, String passwd, String driver, String db) {
        this.jdbcUrl = jdbcUrl;
        this.user = user;
        this.passwd = passwd;
        this.driver = driver;
        this.db = db;
    }

    public void run() {
        long start = System.currentTimeMillis();
        Connection c = null;
        PreparedStatement ps = null;
        int TOTAL_RECS = 100000; // 100000;
        int BATCH_SIZE = 1024; // 500
        
        try {
            Class.forName(driver);
            c = DriverManager.getConnection(jdbcUrl, user, passwd);
            System.out.println("connection obtained successfully for the db " + db);
//            TestUtil.executeQueriesFromFile(c, "./sql/TestGitHubBug31.sql");
            c.setAutoCommit(false);
            ps = c.prepareStatement("insert into batchperftest values (?, ?)");
            int batchSize = 0;
            int batchId = 1;
            for (int i = 1; i <= TOTAL_RECS; i++) {
                ps.setInt(1, i);
                ps.setString(2, "abcdefghijklmnopqrstuvwxyz-" + i);
                ps.addBatch();
                batchSize++;
                if (batchSize == BATCH_SIZE) {
                    batchSize = 0;
                    ps.executeBatch();
                    c.commit();
                    System.out.println("completed inserting batch-" + (batchId++) +
                            " for the db " + db);
                }
            }
            long end = System.currentTimeMillis();
            System.out.println("completed successfully for the db " + db + " in " +
                    (end - start) + " millisecs");
        } catch (Throwable t) {
            t.printStackTrace();
        } finally {
            try {
                if (ps != null) {
                    ps.close();
                }
            } catch (Throwable t1) {

            }
            if (c != null) {
                try {
                    c.close();
                } catch (Throwable t2) {

                }
            }
        }
    }
}

**Comment by iggarish** [comment]
Closing the issue. Please re-open if you still see the issue.

**Comment by Syed-SnapLogic** [comment]
Thank you very much @iggarish.  The info you provided is very helpful.
