### ISSUE TITLE
Users can see all schemas even if they don't have USAGE or SELECT permissions

### ISSUE THREAD

**Issue by daniel-mode** [aws/amazon-redshift-jdbc-driver#32]
## Driver version
2.0.0.7

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.29551

## Client Operating System
OSX

## JAVA/JVM version
1.8.0

## Table schema
Any table schema

## Problem description
Any user in a database can see all schemas when calling `connection.getMetaData().getColumns`, even if they don't have `USAGE` or `SELECT` permissions. I tested with a sample user and revoked all select and usage for a `test_schema`, and the user could still see the restricted schema, but without select permissions.
1. Expected behaviour:
Users should only see the schemas for which they have `USAGE` or `SELECT` permission.
2. Actual behaviour:
Users can see all schemas even if they don't have `USAGE` or `SELECT` permission over them
3. Error message/stack trace:
N/A
4. Any other details that can be helpful:
I tested the query the driver is using on a SQL IDE and the same wrong behavior is observed. This query is based on SVV_* TABLES or `pg_namespace` depending on the Schema pattern type. Both variants display the same wrong behavior.
If `information_schema` is used, the correct behavior is observed.

## JDBC trace logs
N/A

## Reproduction code
```
CREATE USER test_user1 PASSWORD 'Test_user1';
CREATE SCHEMA dev.test_schema AUTHORIZATION awsuser;
REVOKE USAGE ON SCHEMA test_schema from test_user1;
REVOKE SELECT ON ALL TABLES IN SCHEMA "test_schema" FROM test_user1;
```

Connect as `test_user1` and run: `select * from svv_tables where table_schema != 'pg_catalog' and table_schema != 'information_schema';`
The schema `test_schema` will be listed.

If you run `SELECT distinct t.table_schema FROM information_schema.tables t` the `test_schema` will not appear.

If you run 
```
GRANT USAGE ON SCHEMA test_schema TO test_user1;
GRANT SELECT ON ALL TABLES IN SCHEMA "test_schema" TO test_user1;
```
Both queries, on `svv_tables` and `information_schema` will show the `test_schema`

**Comment by iggarish** [comment]
Thanks for reporting the issue. Looks like server issue. I will talk to server team.

**Comment by iggarish** [comment]
Created issue with server team: RedshiftDP-32427

**Comment by daniel-mode** [comment]
Thank you @iggarish, where can I track the progress of the server issue?

**Comment by iggarish** [comment]
We open source only drivers. Redshift server code is closed source. So please report to Redshift support team to track it. I am closing this issue as it's not a driver issue.
