### ISSUE TITLE
Unable to execute a stored procedure with REF_CURSOR OUT parameter

### ISSUE THREAD

**Issue by Syed-SnapLogic** [aws/amazon-redshift-jdbc-driver#33]
## Driver version
2.0.0.7

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.29551

## Client Operating System
18.04.5 LTS (Bionic Beaver)

## JAVA/JVM version
openjdk version "11.0.9.1" 2020-11-04

## Table schema
create table syedsptest1(id int, name varchar(20));

## Problem description
Created a stored procedure as follows:
`CREATE OR REPLACE PROCEDURE sp_syedproc3 (param IN integer, rs_out INOUT refcursor)
    AS $$
    BEGIN
       OPEN rs_out FOR SELECT * FROM syedsptest1 where id >= param;
    END;
    $$ LANGUAGE plpgsql;
    / `

Able to invoke the above procedure thru a client tool squirrel sql client.
`begin;
    call sp_syedproc3(2, 'spcursor2');
    fetch 1000 from spcursor2;
    commit;`

However, unable to execute the above procedure thru JDBC using both Statement and CallableStatement.

Thru Statement:

`Class.forName("org.postgresql.Driver");
        Connection c = DriverManager.getConnection(
                "jdbc:postgresql://<host>:5439/<db>?ssl=true&sslfactory=org.postgresql.ssl.DefaultJavaSSLFactory",
                "<user>", "<passwd>");
        Statement s = c.createStatement();
        ResultSet rs = s.executeQuery("call sp_syedproc3(2, 'spcursor2')");
        rs.setFetchSize(10);
        while (rs.next()) {
            System.out.println(rs.getObject(1));
        }
        System.out.println("successful");
        rs.close();
        s.close();
        c.close();`

Gets error **"Exception in thread "main" org.postgresql.util.PSQLException: ERROR: Fetch ALL is not supported on single-node clusters. Please specify the fetch size (maximum 1000 for single-node clusters) or upgrade to a multi node installation."**.

Thru CallableStatement:

`Class.forName("com.amazon.redshift.jdbc42.Driver");
        Connection c = DriverManager.getConnection(
                "jdbc:redshift://<host>:5439/<db>",
                "<user>", "<passwd>");
        CallableStatement s = c.prepareCall("{call sp_syedproc3(?, ?)}");
        s.setInt(1, 2);
        s.registerOutParameter(2, Types.REF_CURSOR);
        s.executeQuery();
        System.out.println("success");
        s.close();
        c.close();`

Gets error **"Exception in thread "main" com.amazon.redshift.util.RedshiftException: ERROR: procedure sp_syedproc3(integer) does not exist
  Hint: No procedure matches the given name and argument types. You may need to add explicit type casts."**.

Can I please be guided on how to get the procedure executed thru Statement/CallableStatement if thats supported as of today?

**Comment by iggarish** [comment]
Thx for reporting issue. We will look into RedshiftException.

**Comment by iggarish** [comment]
Can you try adding IN parameter value of REF_CURSOR using CallableStatement? e.g. s.setString(2, "my_cursor");

**Comment by Syed-SnapLogic** [comment]
@iggarish , thanks for the suggestion.  I tried it out, and I ended up getting the same exception as without CallableStatement.
![image](https://user-images.githubusercontent.com/5888194/130192366-f4e52555-7e02-4282-810e-532cd89e41c9.png)

**Comment by Syed-SnapLogic** [comment]
And I could finally get a multi-node redshift cluster to see if it works there since the error message says "try multi-node cluster".
However, I am getting different error now.


![image](https://user-images.githubusercontent.com/5888194/130194929-b08d98f7-22e3-463e-9e40-cdf7c6367d4d.png)

Any help to get ref_cursor working be it single/multi node cluster would be great.

**Comment by Syed-SnapLogic** [comment]
Any update on this @iggarish ? thanks.

**Comment by iggarish** [comment]
I will reproduce the issue this week and let you know outcome of it.

**Comment by iggarish** [comment]
I tried to reproduce the issue. I got different error. For that error I open the server ticket:RedshiftDP-32610
I am getting following error:
sql:{ call sp_proc3(?, ?)} nativesql:{ call sp_proc3($1, $2)}
Exception in thread "main" com.amazon.redshift.util.RedshiftException: ERROR: cursor "mycursor" does not exist
        at com.amazon.redshift.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2601)
        at com.amazon.redshift.core.v3.QueryExecutorImpl.processResultsOnThread(QueryExecutorImpl.java:2269)
        at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1880)
        at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1872)
        at com.amazon.redshift.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
        at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeInternal(RedshiftStatementImpl.java:514)
        at com.amazon.redshift.jdbc.RedshiftStatementImpl.execute(RedshiftStatementImpl.java:435)
        at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeWithFlags(RedshiftStatementImpl.java:376)
        at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeCachedSql(RedshiftStatementImpl.java:362)
        at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeWithFlags(RedshiftStatementImpl.java:339)
        at com.amazon.redshift.jdbc.RedshiftConnectionImpl.execSQLQuery(RedshiftConnectionImpl.java:573)
        at com.amazon.redshift.jdbc.RedshiftResultSet.internalGetObject(RedshiftResultSet.java:283)
        at com.amazon.redshift.jdbc.RedshiftResultSet.getObject(RedshiftResultSet.java:3046)
        at com.amazon.redshift.jdbc.RedshiftCallableStatement.executeWithFlags(RedshiftCallableStatement.java:131)
        at com.amazon.redshift.jdbc.RedshiftPreparedStatement.execute(RedshiftPreparedStatement.java:184)
        at TestCallableg33.executeCallable(TestCallableg33.java:35)
        at TestCallableg33.main(TestCallableg33.java:19)

**Comment by iggarish** [comment]
Here is my sample program:
public class TestCallableg33 {

	public static void main(String[] args) throws SQLException, IOException {
		Connection connection = null;
		try {
			TestCallableg33 ts = new TestCallableg33();
			connection = TestUtil.getConnection();
//			TestUtil.executeQueriesFromFile(connection, "./sql/test_g33.sql");
//			TestUtil.executeOneQueryInFile(connection, "./sql/test_g33_2.sql");
			ts.executeCallable(connection, "{ call sp_proc3(?, ?)}");
//			ts.executeCallWithPrepare(connection, "call test_sp2('mycursor')");
		}
		finally {
			if (connection != null)
				connection.close();
		}
	}
	
	private void executeCallable(Connection connection, String sql) throws SQLException {
		String nativeSQL = connection.nativeSQL(sql);
		System.out.println("sql:" + sql + " nativesql:" + nativeSQL);
		CallableStatement cstmt = connection.prepareCall(sql);
		cstmt.setInt(1, 2);
		cstmt.setString(2, "mycursor");
		cstmt.registerOutParameter(2, Types.REF_CURSOR);
		cstmt.execute();
		
		cstmt.close();
	}
}

test_g33.sql:
create table sptest1(id int, name varchar(20));
insert into sptest1 values(1,'aaaa');
insert into sptest1 values(2,'bbb');
insert into sptest1 values(3,'ccc');

test_g33_2.sql:
CREATE OR REPLACE PROCEDURE sp_proc3 (param IN integer, rs_out INOUT refcursor) 
  AS $$ 
BEGIN 
    OPEN rs_out FOR SELECT * FROM sptest1 where id >= param; 
END; 
$$ LANGUAGE plpgsql;

**Comment by iggarish** [comment]
Yes your last error "rs_out" cursor not found matches my error. So we need to wait until server team look into it. It's not the driver issue.

**Comment by Syed-SnapLogic** [comment]
Any update on this @iggarish ?

**Comment by iggarish** [comment]
Hi Syed,

As this is not driver issue and server side issue. Please open up ticket with Redshift support and mention: https://sim.amazon.com/issues/RedshiftDP-32777 as a reference.

Sorry we can't track server issue here in github. So I am closing this issue here.

Thanks,
ilesh Garish

**Comment by Syed-SnapLogic** [comment]
Thanks for the help @iggarish .
