### ISSUE TITLE
Missing com.amazon.redshift:redshift-jdbc42-no-awssdk in Maven

### ISSUE THREAD

**Issue by vbmacher** [aws/amazon-redshift-jdbc-driver#34]
## Driver version
1.2.55.1083

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.29551

## Client Operating System
Linux

## JAVA/JVM version
java version "1.8.0"

## Table schema
N/A

## Problem description
1. Expected behaviour:
Package `com.amazon.redshift:redshift-jdbc42-no-awssdk` will be in Maven central (or in Mulesoft repository https://repository.mulesoft.org/nexus/content/repositories/public/com/amazon/redshift/redshift-jdbc42-no-awssdk/ as it was until Wed 15th september 2021)

2. Actual behaviour: All versions of `redshift-jdbc42-no-awssdk` are missing in Mulesoft and Maven repository. Only plain `redshift-jdbc42` is available.

## Reproduction code
When using SBT:

```
libraryDependencies += "com.amazon.redshift" % "redshift-jdbc42-no-awssdk" % "1.2.55.1083"
```

**Comment by iggarish** [comment]
We never put 1.x JDBC driver in Maven central. Now we have 2.x JDBC driver, which we are uploading to Maven central. So closing the issue as open source driver is 2.x.
