### ISSUE TITLE
Error with parameterized LIMIT using BigInt

### ISSUE THREAD

**Issue by alberto-fernandez-otm** [aws/amazon-redshift-jdbc-driver#37]
## Driver version
2.1.0.1

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.31651

## Client Operating System
Mac OS X

## JAVA/JVM version
8, 11

## Problem description
Cannot send BigInteger as binding for a parameterized LIMIT. We use Clojure, and clojure uses BigInt by default for literal numbers, so the following statement sends a BigInteger as the limit:
```clojure
(jdbc/query rdb ["SELECT * FROM table LIMIT ?" 100])
```
And we are receiving the following error:
```
;   Detail: 
  -----------------------------------------------
  error:  Not implemented
  code:      1001
  context:   'IsA(cons, Const)' - 
  query:     1573873
  location:  pg_utils.cpp:6213
  process:   padbmaster [pid=25361]
  -----------------------------------------------
```

When explicitly coercing to Integer, it works

```clojure
(jdbc/query rdb ["SELECT * FROM table LIMIT ?" (int 100)])
```

Is this expected behaviour and thus all Limit should be ensured to be ints, or is it a bug? We were not having this problem with version 1.x of the driver, we recently upgraded to 2.1 and this happened.

**Comment by iggarish** [comment]
Released the fix in 2.1.0.2 version.
