### ISSUE TITLE
How to handle julian->gregorian calendar switch? 

### ISSUE THREAD

**Issue by ebyhr** [aws/amazon-redshift-jdbc-driver#40]
## Driver version
2.1.0.3

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.34355

## Client Operating System
Mac OS Monterey 12.0.1

## JAVA/JVM version
Java 11.0.12

## Table schema
c1 date

## Problem description
I would like to get missing dates during julian->gregorian calendar switch without casting to string in Redshift side.

## JDBC trace logs
n/a

## Reproduction code
Tried getString, getDate, getObject(LocalDate) and getTimestamp, but all of them returned 1582-10-15 (not 1582-10-05). 
I know `TO_CHAR` function returns the correct result as string, but I don't want to use it.
```java
        Connection connection = DriverManager.getConnection(JDBC_URL, USER, PASSWORD);
        Statement statement = connection.createStatement();

        statement.execute("DROP TABLE IF EXISTS est_date");
        statement.execute("CREATE TABLE test_date (c1 date)");
        statement.execute("INSERT INTO test_date VALUES ('1582-10-05')");
        ResultSet rs = statement.executeQuery("SELECT * FROM test_date");
        while (rs.next()) {
            // returns 1582-10-15
        }

```

**Comment by iggarish** [comment]
Thanks for reporting issue. We will look into it.

**Comment by iggarish** [comment]
As column is DATE type, application treat value as java.sql.Date. Per definition this class represents: A milliseconds value represents the number of milliseconds that have passed since January 1, 1970.
https://docs.oracle.com/javase/8/docs/api/java/sql/Date.html

So looks like TO_CHAR is the way to go or if you have home grown application use resultset.getString() method.

**Comment by ebyhr** [comment]
@iggarish I would recommend providing the right value via `ResultSet.getObject(, Class<T> type)`.

**Comment by ebyhr** [comment]
@iggarish Please reopen this issue.

**Comment by iggarish** [comment]
what's the Class<T> type can be use here?

**Comment by ebyhr** [comment]
@iggarish MySQL and PostgreSQL JDBC return correct values via `LocalDate`.

**Comment by bhvkshah** [comment]
This is a known issue in the switch from the Julian to Gregorian calendars in Java as explained here: https://stackoverflow.com/questions/23975205/why-does-converting-java-dates-before-1582-to-localdate-with-instant-give-a-diff and here: https://stackoverflow.com/questions/23457470/calendar-to-date-conversion-for-dates-before-15-oct-1582-gregorian-to-julian-ca

As a workaround, you can perform a cast on your query when fetching such as: 
`SELECT CAST(c1 AS TIMESTAMP) FROM test_date`

And then get the right date via:
`ResultSet.getObject(, LocalDate.class)`

**Comment by ebyhr** [comment]
@bhvkshah I knew the workaround, see the description. I would recommend checking other JDBC drivers' implementation more.

**Comment by bhvkshah** [comment]
@ebyhr PG JDBC has this implementation which already exists in Redshift JDBC Driver: https://github.com/pgjdbc/pgjdbc/issues/1534

Could you point me towards a specific driver's code which has the fix you would like to see implemented?

**Comment by ebyhr** [comment]
@bhvkshah 
Please take a look at  https://github.com/pgjdbc/pgjdbc/blob/96824b0693e7dcf209fb16f909c3cabfb125c240/CHANGELOG.md#4234-2022-04-01-141628--0400

**Comment by bhvkshah** [comment]
Thanks for the additional information, we will take a look

**Comment by bhvkshah** [comment]
Hi @ebyhr , we will not be pursuing this issue in the near future, and have decided to close it for now. It will be reopened if we come back to this issue. The Redshift Driver team appreciates your contribution and thanks you for bringing this to our attention!
