### ISSUE TITLE
reWriteBatchedInserts with executeBatch doesn't return the correct count

### ISSUE THREAD

**Issue by mageshn** [aws/amazon-redshift-jdbc-driver#44]
## Driver version
v2.1.0.4 . Guess happens in all versions

## Redshift version

PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.35480

## Client Operating System

Mac

## JAVA/JVM version

Java 11

## Table schema

Any Schema

## Problem description
When I try to set the reWriteBatchedInserts to true and invoke executeBatch() on the Prepared statement it does't return the updated count. All the array elements have a value of -2. This works fine if I don't set the reWriteBatchedInserts. 

## JDBC trace logs

N/A

## Reproduction code
        Connection connection = DriverManager.getConnection(
                String.format(
                        "jdbc:redshift://%s:%s/%s?reWriteBatchedInserts=true",
                        "test",
                        "5439",
                        "test"),
                "test",
                "test");

        connection.setAutoCommit(false);
        Statement statement = connection.createStatement();
        statement.execute(" CREATE TABLE IF NOT EXISTS \"Repro_Batch\" ( \"c0\" VARCHAR(MAX) );");
        connection.commit();

        PreparedStatement insert = connection.prepareStatement("INSERT INTO \"Repro_Batch\" ( \"c0\" ) VALUES (?)");

        for (int i=0; i<100 ; i++) {
            insert.setString(1, "prefix-"+i);
            insert.addBatch();
        }
        int[] count = insert.executeBatch();
        connection.commit();
        int totalUpdates = IntStream.of(count).sum();
        assert totalUpdates==100 ;

**Comment by iggarish** [comment]
-2 represents Statement.SUCCESS_NO_INFO. We don't have individual batch count right now. we will see if we get it from server and how to implement it.

**Comment by mageshn** [comment]
@iggarish Thanks a lot for your reply. Another behavior I noticed was that if the batch has even number of records all of the response has Statement.SUCCESS_NO_INFO whereas if it is odd everything except the last has one -2 and the last one is 1. Is this expected and is this a documented behavior? Does reWriteBatchedInsertsSize have any impact on this?

**Comment by iggarish** [comment]
executeBatch() API has this expectation:
Returns:
an array of update counts containing one element for each command in the batch. The elements of the array are ordered according to the order in which commands were added to the batch.

So you added 100 batch. Now because of reWrite, this actually becomes 3 batches (64, 32 ,4). So now driver can't return array of 3 elements. It returns array of 100 elements and saying that SUCCESS_NO_INFO for each of that element.

**Comment by iggarish** [comment]
As such you can't do: IntStream.of(count).sum(). Because each element in return array can have one of the following value:
1. A number greater than or equal to zero
2. SUCCESS_NO_INFO
3. EXECUTE_FAILED

**Comment by mageshn** [comment]
That was just a sample I had but when I had a batch size of 101, 100 of those had -2 as the return and the lats one had a return value of 1. This was happening only when the batch size is 1. Is this expected?

**Comment by iggarish** [comment]
Yes when batch size is one then there is no specials logic and count should return for  that single execution.

**Comment by mageshn** [comment]
> Yes when batch size is one then there is no specials logic and count should return for that single execution.

If the batch size is 101 - It should get divided into (64,32,5 ), right? If yes, I would expected to see SUCCESS_NO_INFO for all the 101 records but I see SUCCESS_NO_INFO for 100 and 1 for the the 101th record which makes me believe that the it is broken into (64, 32, 4, 1). So, each batch size here is a power of 2. Is that how it works?

**Comment by iggarish** [comment]
Yes each batch is power of 2.

**Comment by iggarish** [comment]
But main issue is reWrite reduce the original number of batches provided by application. So we can't return actual count in original number of batches, because driver has count for each reduce batches.

**Comment by iggarish** [comment]
We won't get count as needed in batch re-write. closing the issue.
