### ISSUE TITLE
Driver.getPropertyInfo missing new properties added to Redshift 2.1.x driver

### ISSUE THREAD

**Issue by dqmdev** [aws/amazon-redshift-jdbc-driver#50]
## Driver version
2.1.0.5

## JAVA/JVM version
8

## Problem description
Driver.getPropertyInfo method does not return new properties added regarding tokens.
https://docs.oracle.com/javase/8/docs/api/java/sql/Driver.html#getPropertyInfo-java.lang.String-java.util.Properties-

An application, such as SQLsquirrel creates a UX based on introspecting the response from the driver.
If a property is not defined, then it is not listed in their UX.

i.e.
client_id
idp_tenant
scope

https://aws.amazon.com/blogs/big-data/integrate-amazon-redshift-native-idp-federation-with-microsoft-azure-ad-using-a-sql-client/

![image](https://user-images.githubusercontent.com/54872285/164456203-3e9e5a7a-d63c-4811-aea3-6ef717669e1c.png)

 Properties info = new Properties();
 DriverPropertyInfo[] dbProp = driver.getPropertyInfo( dbMeta.getURL(), info);

**Comment by iggarish** [comment]
Thanks for reporting issue. We will look into it.

**Comment by bhvkshah** [comment]
Hi @dqmdev , we will not be pursuing this issue in the near future, and have decided to close it for now. It will be reopened if we come back to this issue. The Redshift Driver team appreciates your contribution and thanks you for bringing this to our attention!

**Comment by dqmdev** [comment]
This was feedback given to the Amazon Redshfit team (driver developer I think has since left) regarding "challenges" encountered.
Long story short, to avoid mutual customers struggling and in turn being forced to open support calls etc.
