### ISSUE TITLE
Internal Jar files in Maven based projects using amazon-redshift-jdbc-driver

### ISSUE THREAD

**Issue by normanj-bitquill** [aws/amazon-redshift-jdbc-driver#51]
## Driver version
2.1.0.6

## Redshift version
Redshift version does not matter.

## Client Operating System
OS should not matter here. Issue is about Maven builds.

## JAVA/JVM version
JVM version should not matter, anything supported by this project is fine.

## Table schema
N/A

## Problem description
The 2.1.x versions of this project depend on some internal Amazon Jar files.

- aws-java-sdk-redshift-internal-1.12.x.jar
- aws-java-sdk-redshift-arcadia-internal-1.0.jar

These files are not available in Maven. It is unclear how to include these files. They do not have licenses, and extra steps are needed to download them in a Maven build.

What is the recommended approach for using a 2.1 release and including these Jar files in a Maven project?

1. Expected behaviour:
Can include amazon-redshift-jdbc-driver as a Maven dependency and it works at runtime without any ClassNotFoundExceptions.
2. Actual behaviour:
Classes from the internal Jars are missing, and can throw ClassNotFoundExceptions at runtime.
3. Error message/stack trace:
`java.lang.NoClassDefFoundError: com/amazonaws/services/redshiftinternal/AmazonRedshiftInternalClientBuilder
    at com.amazon.redshift.jdbc.RedshiftConnectionImpl.<init>(RedshiftConnectionImpl.java:262)
    at com.amazon.redshift.Driver.makeConnection(Driver.java:492)
    at com.amazon.redshift.Driver.connect(Driver.java:305)
    at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
    at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:260)
    at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:2337)
    at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2323)
    at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:2056)
    at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1533)
    ...`
4. Any other details that can be helpful:

## JDBC trace logs
N/A

## Reproduction code
N/A

**Comment by iggarish** [comment]
Yes , we are aware of this issue. These two jars are right now internals and not publish in Maven. We are pursing in AWS to make it available in Maven. But in the mean time, please get two jars from source "lib" directory and install it in Maven, if you can. Sorry for any inconvenience.

**Comment by normanj-bitquill** [comment]
Thank you for the response. Do you know the license for the internal Jar files? Can they be distributed in a commercial product?

**Comment by iggarish** [comment]
Let me check on it. Mostly it should not be an issue.

**Comment by laurentgo** [comment]
Assuming that the license of the internal jars allow it, would it be possible to shade their content into the main jar (like it is being done with the onscram libraries)?

Actually when checking the pom.xml file in Maven Central (https://repo1.maven.org/maven2/com/amazon/redshift/redshift-jdbc42/2.1.0.6/redshift-jdbc42-2.1.0.6.pom), it doesn't mention any dependency to the internal jars, but when building the driver locally, the reduced pom generated by `maven-shade-plugin` keeps those dependencies.

**Comment by iggarish** [comment]
Please check build.gradle file. It has dependencies. We recommend to use Gradle for building. For question about internal jar deployments, we are working to get rid of it. So keep that in mind and not recommend to deploy the stuff which is going away. We keep dependencies out of the main jar because that way it's clear what's in use if any CVE found.

**Comment by normanj-bitquill** [comment]
@iggarish We might need to upgrade to the 2.1.x release before you have phased out the internal Jars. Can we include the internal Jar files in a commercial product?

**Comment by iggarish** [comment]
Sure, you can. But keep in mind we stop distributing internal jar anytime soon.

**Comment by iggarish** [comment]
We are working on get rid of internal jars. Mostly next release 2.1.0.9 won't have it. I will update here when it happens. Plan the release for first week of July.

**Comment by normanj-bitquill** [comment]
Thank you for the update.

**Comment by iggarish** [comment]
2.1.0.9 released.
