### ISSUE TITLE
NUMERIC/DECIMAL and REAL data type columns loses scale or returns incorrect data type for EXTERNAL tables

### ISSUE THREAD

**Issue by Shashikant-Jaiswal** [aws/amazon-redshift-jdbc-driver#53]
## Driver version

Tested with 2.0.0.0 and 2.1.0.7. But I think it fails with all the 2.x versions.

## Redshift version

PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.38361

## Client Operating System

Ubuntu 18.04.5 LTS

## JAVA/JVM version

openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-8u312-b07-0ubuntu1~18.04-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)

## Table schema

1. Create an external schema
```
        CREATE EXTERNAL SCHEMA ext_schema_test
        from data catalog
        database '<database_name>'
        region '<aws region>'
        iam_role 'arn:aws:iam::<role name>'
        CREATE EXTERNAL DATABASE IF NOT EXISTS;
```

2. Create a .csv file on a S3 path with below contents:
```
,,,,,,,,,,,
test,hello,1,2,3,6.0,7.1,8.23,2017-06-01 18:19:03,char,true,10.00
```

3. Create an external table in the newly created external schema pointing to the CSV file as below:

          CREATE EXTERNAL TABLE <external_schema_name>.<external_table_name> (
            varchar_col VARCHAR(20),
            text_col TEXT,
            smallint_col SMALLINT,
            int_col INT,
            bigint_col BIGINT,
            double_col FLOAT8,
            numeric_col NUMERIC(10,2),
            decimal_col DECIMAL(10,2),
            timestamp_col TIMESTAMP,
            char_col CHAR(10),
            bool_col BOOL,
            real_col REAL
          )
          ROW FORMAT DELIMITED
          FIELDS TERMINATED BY ','
          STORED AS TEXTFILE
          LOCATION '<s3 file path>';

## Problem description

1. Expected behavior:
       The columns with datatype NUMERIC(10,2), DECIMAL(10,2) and REAL should return correct data type id, data type
        name, precision and scale when column metadata is fetched via JDBC. 

```
   DatabaseMetaData metadata = conn.getMetaData();
   ResultSet rs = metadata.getColumns(catalogName, schemaName, tableName, null))
```

       decimal(10,2) --> scale should be returned as 2. But jdbc returns 0.
       numeric(10,2) --> scale should be returned as 2. But jdbc returns 0.
       real --> data type name should be returned as float4. But jdbc returns float.

       Please note that the issue is with only **EXTERNAL** tables. Regular tables work fine.

2. Actual behaviour:
            Explained above.

3. Error message/stack trace:
             N/A

4. Any other details that can be helpful:

**Comment by iggarish** [comment]
Thanks for reporting issue. We will get back to you ASAP. In the mean time if you can generate driver logs that will be helpful to troubleshoot the issue.

**Comment by iggarish** [comment]
We have similar issue in our internal system: D45693084. It's under investigation. I will update here findings about it.

**Comment by Shashikant-Jaiswal** [comment]
@iggarish Thanks for update. May I request an ETA for the resolution?

**Comment by iggarish** [comment]
We have a fix and will get release as part of next release. It's plan for second week of June.

**Comment by iggarish** [comment]
Fix in 2.1.0.8 driver release. Check the Readme for download links.

**Comment by Shashikant-Jaiswal** [comment]
> Fix in 2.1.0.8 driver release. Check the Readme for download links.

@iggarish I tried the latest version 2.1.0.8 and see that the issue is still not resolved. Could you please take a look?

**Comment by iggarish** [comment]
Sorry about that. We will take a look.

**Comment by iggarish** [comment]
Sorry for the delay. We will get back to you ASAP.

**Comment by Shashikant-Jaiswal** [comment]
@iggarish May I request an update on this please? I can create a support ticket if you can help me with the instructions on how to do it?

**Comment by Shashikant-Jaiswal** [comment]
@iggarish could you please confirm if this issue has been fixed?

**Comment by iggarish** [comment]
The scale issue has been fix and will be included in next release.

**Comment by Shashikant-Jaiswal** [comment]
Great. May I know the probable release date and jdbc version which includes this fix?

**Comment by iggarish** [comment]
We will release it in 2.1.0.10, which is plan for end of Aug. For FLOAT v/s REAL datatype issue, we created internal ticket with server team: RedshiftDP-40154. Please follow-up with support for it, as it's not the driver issue.

**Comment by Shashikant-Jaiswal** [comment]
Thank you @iggarish for the update. Has the release date for 2.1.0.10 been finalized yet? Also, May I know where could I follow up with the server team?

**Comment by Brooke-white** [comment]
Hi @Shashikant-Jaiswal , my apologies for the lapse in communication. We are targeting end of next week (November 18th) for JDBC 2.1.0.10. As for following up with the Redshift Server team I'd recommend opening a ticket with support and referencing "RedshiftDP-40154".

**Comment by Shashikant-Jaiswal** [comment]
Thank you @Brooke-white for the update. May I know how to open a ticket with Redshift Server team?

**Comment by Brooke-white** [comment]
@Shashikant-Jaiswal , you can follow the instructions here: https://docs.aws.amazon.com/awssupport/latest/user/case-management.html

**Comment by Shashikant-Jaiswal** [comment]
@Brooke-white thank you for pointing me in the right direction. 
Is JDBC 2.1.0.10 released? not able to find it in the github: https://github.com/aws/amazon-redshift-jdbc-driver.

**Comment by Brooke-white** [comment]
Hi @Shashikant-Jaiswal , we are seeing some delay in our release pipeline so have not release JDBC 2.1.0.10 as was planned. the team is working on the release and i will update once available.
