### ISSUE TITLE
The required connection property does not found ClusterID

### ISSUE THREAD

**Issue by tobyayre** [aws/amazon-redshift-jdbc-driver#54]
## Driver version
2.1.0.7

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.38431

## Client Operating System
Windows 10

## JAVA/JVM version
11.0.12

## Table schema
N/A

## Problem description
The standard connection paramaters are incompatible with Serverless clusters when using IAM authentication and connecting via a network load balancer (NLB).

1. Expected behaviour:
It should be possible to connect with the connection string jdbc:redshift:iam://{nlb-host}:5439/dev?AccessKeyID={xx}&SecretAccessKey={xx}

2. Actual behaviour:
Error message received

3. Error message/stack trace: 
The required connection property does not found ClusterID

4. Any other details that can be helpful: 
I managed to overcome this issue and successfully connect by adding 'isServerless=true' to the connection string. However, this parameter is not mentioned anywhere in the Redshift docs.

**Comment by iggarish** [comment]
Thanks for reporting issue. We will get back to you ASAP. In the mean time if you can generate driver logs that will be helpful to troubleshoot the issue. Please don't use undocumented property. This may be because driver detect serverless end point by looking at host and it should contains "redshift-serverless". Now you use NLB, so it thinks you connect to provision cluster. Need to check with team how to detect incase of NLB.

**Comment by iggarish** [comment]
Hi Toby, I discuss with team. We are going to expose new connection properties for serverless in case NLB where driver can't get needed information from the URL. So we will expose isServerless, account_id, work_group etc. as new connection properties. I know, you use internal property to work around. But we will expose new set of properties as officially supported.

**Comment by iggarish** [comment]
Fix in 2.1.0.8 driver release. Check the Readme for download links.

**Comment by hkuchibhotla** [comment]
> 4\. 'isServerless=true'

is this available? We are running into the same issue with serverless redshift & NLB URL in the connection string. None of the workarounds above seem to work. 

Using 2.1.0.28

**Comment by hkuchibhotla** [comment]
> 4\. isServerless=true

this doesn't seem to work with redshift serverless fronted by the NLB
