### ISSUE TITLE
It is not possible to expand the database tree for external schemas in Redshift Serverless when authenticating with IAM

### ISSUE THREAD

**Issue by tobyayre** [aws/amazon-redshift-jdbc-driver#56]
## Driver version
2.1.0.7

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.38431

## Client Operating System
Windows 10

## JAVA/JVM version
11.0.12

## Table schema
N/A

## Problem description
When authenticating to Redshift Serverless using IAM and connecting via a NLB, it is not possible to expand the database tree to view the tables and views in an external schema created from a datashare.

1. Expected behaviour:
a. Open DBeaver or Coginiti Pro and create the connection e.g. jdbc:redshift:iam://{nlb-host}:5439/dev?isServerless=true&Profile=my-profile
b. Establish a connection
c. Expand the database tree
d. See which tables and views are in an external schema created from a datashare

2. Actual behaviour:
Steps A and B work (except the limitations described in [issue 54](https://github.com/aws/amazon-redshift-jdbc-driver/issues/54) and [issue 55](https://github.com/aws/amazon-redshift-jdbc-driver/issues/55)). Steps C and D do not work

3. Error message/stack trace:
none

4. Any other details that can be helpful:
N/A

**Comment by iggarish** [comment]
Maneesh work with you and it's not the driver issue but privilege's issue. So closing the issue as we have internal tickets to track for server side issues.
