### ISSUE TITLE
NPE in Driver.getJdbcIniFile()

### ISSUE THREAD

**Issue by leo-from-spb** [aws/amazon-redshift-jdbc-driver#58]
NullPointerException, the most probably in Driver.java:914
As I could see while debugging, the "Driver.class.getProtectionDomain().getCodeSource().getLocation()" is null, so calling the "getPath()" function from null causes NPE :(

https://github.com/aws/amazon-redshift-jdbc-driver/blob/40b143b4698faf90c788ffa89f2d4d8d2ad068b5/src/main/java/com/amazon/redshift/Driver.java#L914

**Comment by iggarish** [comment]
Thanks for reporting issue. We will take a look.

**Comment by iggarish** [comment]
We fix the issue as you mention. As such we are not able to repro this one. The fix with null check will be release in first week of July in next release 2.1.0.9

**Comment by iggarish** [comment]
2.1.0.9 Released.
