### ISSUE TITLE
fetchRingBufferSize should be global to all the created RingBufferThread in a JVM

### ISSUE THREAD

**Issue by odelpozog** [aws/amazon-redshift-jdbc-driver#62]
### Discussed in https://github.com/aws/amazon-redshift-jdbc-driver/discussions/48

<div type='discussions-op-text'>

<sup>Originally posted by **odelpozog** March 24, 2022</sup>
Hello

Some Denodo Technologies customers are facing java.lang.OutOfMemoryError issues executing Redshift queries in a concurrent way with the Reshift 2.x JDBC drivers. By default, the enableFetchRingBuffer feature is enabled and multiple instances of RingBufferThread are created with 1GB of max size when multiple queries are executed.

When this happens, as the buffers are filling up, the heap memory grows and, eventually, a java.lang.OutOfMemoryError is raised:

![image](https://user-images.githubusercontent.com/44649617/159924935-d9dcbed1-af4d-4ed1-8cca-31b8109fb2ea.png)

I think that the fetchRingBufferSize should limit the total JVM memory used by all the RingBufferThread instances, not the size of each RingBufferThread instance. Otherwise, JDBC clients with concurrent queries should not enable the RingBuffer feature to avoid possible OOM issues.</div>

**Comment by iggarish** [comment]
Thanks for reporting the issue. We will discuss internally and get back to you.

**Comment by jhchee** [comment]
Any resolution for this?

**Comment by bhvkshah** [comment]
@jhchee Sorry for the delay! I will look into this issue and get back to you once i have an update. Thanks for submitting it!

**Comment by bhvkshah** [comment]
Hi @odelpozog  , while we will not be pursuing this issue in the near future, fixing this issue is part of our long term roadmap. We have decided to close it for now. It will be reopened when we come back to this issue. The Redshift Driver team appreciates your contribution and thanks you for bringing this to our attention!
