### ISSUE TITLE
Feature request - Configuration option to disable/ignore external objects for Database Explorer due to Redshift performance impacting user experience

### ISSUE THREAD

**Issue by casey-crawford-cfa** [aws/amazon-redshift-jdbc-driver#64]
## Driver version
https://s3.amazonaws.com/redshift-downloads/drivers/jdbc/2.1.0.9/redshift-jdbc42-2.1.0.9.jar

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.40182

## Client Operating System
macOS Big Sur - 11.5.2

## JAVA/JVM version
openjdk 17.0.1 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)

## Problem description
Using the database explorer to view all objects (`*` schema) takes an incredibly long time to return for several of our clusters. This is variable by usage and number of external objects.

The queries themselves are slow within Redshift:
- select count(*) from svv_external_tables; -- 11,219 rows @ 2m 32s
- select count(*) from svv_tables; -- 19,776 rows @ 2m 21s
- select count(*) from svv_all_tables; -- 18,409 rows @ 2m 26s
- [this query](https://github.com/aws/amazon-redshift-jdbc-driver/blob/40b143b4698faf90c788ffa89f2d4d8d2ad068b5/src/main/java/com/amazon/redshift/jdbc/RedshiftDatabaseMetaData.java#L1608) -- 8,891 rows @ 1.64s

If there were a configuration option to force a specific type of schemaPatternType for [getTables](https://github.com/aws/amazon-redshift-jdbc-driver/blob/40b143b4698faf90c788ffa89f2d4d8d2ad068b5/src/main/java/com/amazon/redshift/jdbc/RedshiftDatabaseMetaData.java#L1569) retrieval, it would alleviate a lot of issues with our user base that is spread across many different tools.

Thank you!

**Comment by bhvkshah** [comment]
Fixed in https://github.com/aws/amazon-redshift-jdbc-driver/pull/65
Will be available in driver version 2.1.0.11
