### ISSUE TITLE
Tag 2.1.0.11 missing

### ISSUE THREAD

**Issue by findinpath** [aws/amazon-redshift-jdbc-driver#81]
Recently there was released a new version for aws redshift jdbc driver

https://github.com/aws/amazon-redshift-jdbc-driver/blob/master/CHANGELOG.md#v21011-2023-02-03

However, it seems that the corresponding tag is missing on the github project.

It also seems that the PR https://github.com/aws/amazon-redshift-jdbc-driver/pull/74 is not referenced on the changelog.

Could you please correct these issues?

**Comment by bhvkshah** [comment]
Thank you for submitting this issue @findinpath. I have re-added the tag for v2.1.0.11 and modified the changelog to reference #74. We appreciate for your contribution to the Redshift JDBC Driver!
