### ISSUE TITLE
Patch version 2.1.0.12 breaking changes (API & behavioral)

### ISSUE THREAD

**Issue by NathanEckert** [aws/amazon-redshift-jdbc-driver#90]
## Driver version
Upgrade from 2.1.0.11 to 2.1.0.12

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.50708

## Client Operating System
Ubuntu 22.04.2 LTS

## JAVA/JVM version
openjdk 11.0.17 2022-10-18
OpenJDK Runtime Environment Temurin-11.0.17+8 (build 11.0.17+8)
OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (build 11.0.17+8, mixed mode)

## Problem description

When upgrading from the driver version 2.1.0.11 to 2.1.0.12, there was a breaking change: the method `RedshiftProperties#parseUrl()` changed signature from `(String, java.util.Properties)` to `(String, RedshiftProperties)` (see https://github.com/aws/amazon-redshift-jdbc-driver/commit/7c807cd2cf1ba7ee5116d2d610f2daf324df3767#diff-9cac02d84c6529eb62db852fd9a951573b50ca9ac28640aeafbe34257f96a6a0R568).

These change was breaking but even after applying the required changes, I stumbled upon another issue.
There were some changes related to the case insensitivity, but those changes are not consistent with the `java.sql.Connection` methods:

```java
    package my.packagename.name;

    import static org.assertj.core.api.Assertions.assertThat;
    
    import com.zaxxer.hikari.HikariConfig;
    import com.zaxxer.hikari.HikariDataSource;
    import com.amazon.redshift.util.RedshiftProperties;
    import java.sql.Connection;
    import java.sql.SQLException;
    import org.junit.jupiter.api.Test;

    @Test
    void testRedshiftDriver() throws SQLException {
        final String connectionString = RedshiftTestConstants.TEST_CONNECTION_STRING;
  
        final String expectedAppName = "an elegant and edgy name";
        final RedshiftProperties prop = new RedshiftProperties();
        prop.setProperty(RedshiftProperty.APPLICATION_NAME.getName(), expectedAppName);
        prop.setProperty(RedshiftProperty.PASSWORD.getName(), RedshiftTestConstants.getRedshiftPassword());
  
        final HikariConfig config = new HikariConfig();
        config.setJdbcUrl(connectionString);
        config.setDataSourceProperties(prop);
        final HikariDataSource dataSource = new HikariDataSource(config);
  
        final Connection connection = dataSource.getConnection();
  
        assertThat(RedshiftProperty.APPLICATION_NAME.getName())
                .isEqualTo("applicationname"); // mismatch with following statement
        assertThat(connection.getClientInfo())
                .hasSize(1)
                .containsEntry(
                        "ApplicationName", // mismatch with previous statement
                        "an elegant and edgy name");
  
        assertThat(connection.getClientInfo(RedshiftProperty.APPLICATION_NAME.getName()))
                .isEqualTo("an elegant and edgy name"); // failure, actual is null
  
    }
```

I was surprised to see such a behavioral change (in addition to the API change) in a patch version.

Also, what is the correct way from now on to retrieve connection info through `java.sql.Connection.getClientInfo` ?

Thanks in advance.

**Comment by bhvkshah** [comment]
@NathanEckert thanks for submitting this issue.

Could you please elaborate how/why are you calling the parseUrl() method?

**Comment by NathanEckert** [comment]
So I realized following-up on that question that `RedshiftProperties#parseUrl()` is in a `util` package and that we should maybe not call it direclty but use it through the more public API `Driver#parseUrl()`, however this method has the same API breaking change.

Our usage is do analyze the provided connection string to disallow certain properties that our application will override to avoid to confuse users:

```java
	private static void rejectApplicationFromConnectionString(final String connectionString) {
		final Properties parameters = Driver.parseURL(connectionString, new Properties());
		if (parameters.containsKey(RedshiftProperty.APPLICATION_NAME.getName())) {
			throw new IllegalStateException("Redshift Application cannot be defined in the URL");
		}
	}
```

**Comment by NathanEckert** [comment]
Hello @bhvkshah,

Any update on this issue ?

**Comment by bhvkshah** [comment]
Hi @NathanEckert sorry for the delay! I'll get back to you soon as I have an update on this!

**Comment by NathanEckert** [comment]
Hello @bhvkshah,

Any update on this issue ?

**Comment by NathanEckert** [comment]
Thanks for the suggestion, I was able to upgrade !
