### ISSUE TITLE
Does Redshift support compressed transfers by JDBC? like MySQL's useCompression=true configuration 

### ISSUE THREAD

**Issue by ZHBingo** [aws/amazon-redshift-jdbc-driver#92]
## Driver version

redshift-jdbc42-2.1.0.17.jar

## Redshift version

PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.51296

## Client Operating System

Windows Server 2022

## JAVA/JVM version

JDK 1.8

## Problem description

1. Expected behaviour:
2. Actual behaviour:
3. Error message/stack trace:
4. Any other details that can be helpful:

**Comment by bhvkshah** [comment]
@ZHBingo Current JDBC Driver does not support compression. Redshift driver team is working towards adding support for compression in upcoming releases.

Thank you for bringing up this question. In the future, please use the discussions section for questions.
