### ISSUE TITLE
Wrong metadata reported for column of type TEXT

### ISSUE THREAD

**Issue by YotillaAntoni** [aws/amazon-redshift-jdbc-driver#98]
## Driver version
2.1.0.19

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.56952

## Client Operating System
MacOS Version 13.6 (22G120)

## JAVA/JVM version
OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)

## Table schema
```
create schema test;

create table test.test_table (
 name text
);

create view test.test_view 
as
 select 'a' || 'b' as name 
;
```

## Problem description
When querying for the metadata of a VIEW with a column of type TEXT a wrong column size of `2147483647` is reported. 
The Redshift [documentation for type TEXT](https://docs.aws.amazon.com/redshift/latest/dg/r_Character_types.html#r_Character_types-text-and-bpchar-types) states that

> You can create an Amazon Redshift table with a TEXT column, **but it is converted to a VARCHAR(256)** column that accepts variable-length values with a maximum of **256** characters.

Indeed if we try to create a table like the one specified in "Table Schema", with a column of type `text`, and then query for the metadata we will get a type (field `type_name`) `varchar` and column size (field `column_size`) of 256.

But if we create a view like the one specified in "Table Schema" with a simple concatenation, then type reported is `text` and the column size is `2147483647`

1. Expected behaviour:
The column type and size reported for a column of type `TEXT` should be `varchar` and `256`.
2. Actual behaviour:
The type and column size reported is `text` and `2147483647` 

## JDBC trace logs
[redshift_jdbc_connection_1.log](https://github.com/aws/amazon-redshift-jdbc-driver/files/12791838/redshift_jdbc_connection_1.log)

## Reproduction code
```
        try (
                Connection conn = DriverManager.getConnection(JDBC_URL, USER, PASSWORD);
                ResultSet resultSet = conn.getMetaData().getColumns("dev", "test", "test_view", null);
        ) {
            while (resultSet.next()) {
                System.out.printf("%s | type_name:%s column_size:%d %n",
                        resultSet.getString("column_name"),
                        resultSet.getString("type_name"),
                        resultSet.getInt("column_size"));
            }
        }
```

**Comment by YotillaAntoni** [comment]
This behaviour I guess it's not really a JDBC bug but an underlying issue with the type assigned to columns. Seems that with the concatenation Redshifts uses the old type TEXT as defined by PostgreSQL, that has unlimited size. This internal PostgreSQL TEXT type doesn't match the definition of the TEXT type by Redshift.

**Comment by bhvkshah** [comment]
Hi @YotillaAntoni , thanks for opening this issue. I have verified that the it is reproducible. However, as this is not a driver issue I have opened an internal ticket with the Redshift server team to look into this. For the same reason, I'm also going to be closing this issue on Github. Again, thank you for your contribution to the Redshift JDBC Driver!

**Comment by YotillaAntoni** [comment]
Thanks @bhvkshah, makes sense. Is there any way to keep track of this kind of issues for the Redshift Server? Or any place to check for fixed issues?

**Comment by bhvkshah** [comment]
As far as I know the only way would be to open a support case with AWS.
